# Generated by Django 6.1.1 on 2026-09-27 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='topics',
            field=models.CharField(blank=True, default='', help_text='Comma-separated topics', max_length=300),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='messages/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt', 'mp4', 'mov', 'webm'])]),
        ),
    ]
